cameras:
  - id: "gate1"
    name: "Въездные ворота"
    rtsp_url: "rtsp://rtsp:cu2W25TpQX3W@192.168.10.18/mode=real&idc=1&ids=1?rtsp_transport=tcp"
    fps: 10
    enabled: false
    motion_enabled: true
    roi: []
    motion_threshold: 0.005
    detector:
      imgsz: 640
  - id: "parking1"
    name: "Парковка 1"
    rtsp_url: "rtsp://rtsp:cu2W25TpQX3W@192.168.10.18/mode=real&idc=6&ids=1?rtsp_transport=tcp"
    fps: 10
    enabled: true
    motion_enabled: true
    roi: []
    motion_threshold: 0.005
    detector:
      imgsz: 640
  - id: "entrance"
    name: "Вход"
    rtsp_url: "rtsp://rtsp:cu2W25TpQX3W@192.168.10.18/mode=real&idc=2&ids=1?rtsp_transport=tcp"
    fps: 10
    enabled: true
    motion_enabled: true
    roi: []
    motion_threshold: 0.005
    detector:
      imgsz: 640
